### ISSUE TITLE
1/2 number of cores used on Azure in Docker

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#1]
When running an update in docker on an Azure cluster only half of the available cores are used. 

Cores are allocated using `setup_future` in `R/utils.R`. This uses `future::availableCores()` internally and should default to all cores when jobs > cores when jobs < cores then the remaining cores should be shared between jobs and used to run multiple MCMC chains. Local tests indicate all of these features are working as intended outside of Azure/script use in docker.

**Comment by joeHickson** [comment]
Interestingly running an R script from a shell script in docker in azure returns the right value.

R/test_avail.R:
```
require(future)
fc <- file("/home/data/test_log.txt")
writeLines(c("Number of cores", future::availableCores()), fc)
close(fc)
```

bin/test_avail.sh:
```
#!/bin/bash

Rscript "R/test_avail.R"
```
/home/data/test_log.txt:
```
Number of cores
64
```

I can repeat the original symptoms though - but part way through the processing it does stack in the remaining cores with processing. Is it possible that there is a nested future loop somewhere that means each region is being allocated two cores but most of the processing is only using one?

**Comment by seabbs** [comment]
Interesting. It could perhaps be how I am setting up the multicore usage (https://github.com/epiforecasts/covid-rt-estimates/blob/cf469e22e51e4f049a3b113f4fcaf22709d25751/R/utils.R#L2) or potentially it's not forcing stan to use 1 core correctly in EpiNow2. There should only be a single parallel call in EpiNow2 (in `regional_epinow`) with any remaining cores used by `estimate_infections` to run multiple MCMC chains. 

What I find very odd is that everything works when used interactively!

**Comment by joeHickson** [comment]
there's some wierdness in that the multicore stuff often has catches on it to change how it runs interactively because rstudio can gets in a grump with multicore. I have seen this in a few places:
'''
if (!interactive()) {
    ## If running as a script enable this
    options(future.fork.enable = TRUE)
  }
'''
and also found reference to some multithreading libs having similar protections.

**Comment by seabbs** [comment]
Yes - I'm adding that to force it to use forking when run in a script from rstudio - otherwise it forces it off. I would have thought it wouldn't make a difference here as its just running in bash on a linux server!

**Comment by joeHickson** [comment]
Not sure what's changed but the latest versions of EpiNow2 seem to be fully utilising the cores (wasn't quick enough to catch it early when they were all running):
![image](https://user-images.githubusercontent.com/8492240/89883941-c09deb00-dbc0-11ea-958d-6113cafb43ef.png)

**Comment by seabbs** [comment]
Interesting! 

So I am still seeing only some cores working when jobs > cores but when cores < jobs I get optimal (or near-optimal usage) as I would expect (with each region getting cores / regions cores. 

I don't think there have been any changes to impact this as I have been mainly focussing on trying to get the website linked in with these estimates (and actually quite distracted  by some UK work). 

If you have some time to look at this I think a sensible debug would be to look at running something else that uses the future setup (i.e one of there examples) and seeing if the `setup_future` function I have written is driving this weird behaviour or if it is internal to `EpiNow2`.

**Comment by joeHickson** [comment]
![image](https://user-images.githubusercontent.com/8492240/89904059-62810000-dbe0-11ea-8cf7-ff8c7f7f147a.png)
I might extend the logging work once it's in to spit out some debug messages about how many cores it is using etc

**Comment by seabbs** [comment]
Well, that looks quite convincing!

**Comment by seabbs** [comment]
So checking a run with everything on the most recent master version I still see this but to less of an extent. Given I recently adapted the `setup_future` function this indicates to me that it is the source of the problem. 

<img width="1433" alt="Screenshot 2020-08-13 at 16 38 22" src="https://user-images.githubusercontent.com/20317649/90155830-ad874880-dd83-11ea-8c82-fd07495610be.png">

**Comment by seabbs** [comment]
I think this is fixed so closing for now
