### ISSUE TITLE
Use dataverse for data up to date (remove the need for last-update/*.rds)

### ISSUE THREAD

**Issue by joeHickson** [epiforecasts/covid-rt-estimates#103]
We could get the latest data from dataverse (latest published data) rather than rely on committing local .rds files.
Blocked by #80 

update the publish script to include the dates for the source data. This is additional data in the get_fields_list function.
```R
list(
            typeName = "timePeriodCovered",
            multiple = TRUE,
            typeClass = "compound",
            value = list(
              list(
                timePeriodCoveredStart = list(
                  typeName = "timePeriodCoveredStart",
                  multiple = FALSE,
                  typeClass = "primitive",
                  value = oldest_data_date
                ),
                timePeriodCoveredEnd = list(
                  typeName = "timePeriodCoveredEnd",
                  multiple = FALSE,
                  typeClass = "primitive",
                  value = newest_data_date
                )
              )
``` 

Update the check_for_update function (utils.R) to handle the checking (probably via a new function). If there are no local .rds files and there is a dataverse config set up then get the "timePeriodCoveredEnd" for the dataset (look at how publish checks for an existing dataset - the same method can be used).
This needs to handle the following as no latest date:
- no config for dataverse
- unable to find a dataset
- unable to find timePeriodCoveredEnd on the dataset

Delete the last-update folder and add it to .gitignore (it will still be generated to allow non-publishing datasets to use it but should only apply to their local datasets)

**Comment by seabbs** [comment]
Sounds like a good idea. Nice!
