### ISSUE TITLE
Code owner + review practice.

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#106]
Discussion issue on code ownership etc for a decision at next catch up. 

As code is stabilized it seems sensible to agree on a code owner for final review of external PRs. @joeHickson as you are leading the Met effort where this code is being run this should likely be you? Or we can have dual code owners met/lshtm and require a review from each? 

Regardless of what the decision is formalising it seems like a good idea.

**Comment by joeHickson** [comment]
Avoiding single points of failure would be sensible but having a list of reviewers (and not reviewing your own work) might be wise.

**Comment by seabbs** [comment]
Agree.
