### ISSUE TITLE
Dataverse not updating

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#114]
Looks like the dataverse is not automatically updating.

**Comment by seabbs** [comment]
Looks like this resolved itself. I guess there is some kind of publishing lag?

**Comment by joeHickson** [comment]
i resolved it, will monitor over the weekend. I think it ight have been newdataset issues but i experienced no problems with the test server...

**Comment by seabbs** [comment]
haha ah nice - thanks :)

**Comment by seabbs** [comment]
very odd. I thought it might the docker inclusion issue again?

**Comment by joeHickson** [comment]
logs were showing a http error code from dataverse but unless it stops things running this weekend I'll save it for monday.

**Comment by seabbs** [comment]
No problem - sounds like potentially an issue on their end.

**Comment by joeHickson** [comment]
picked it up again yesterday - it's almost like harvard had more lag than the test server and that showed up new issues. 
I pushed multiple hot fixes to resolve this as the publication failing triggered more issues downstream (no collation of uk, no summary csv / runtimes).
Notably:
- try wrapper on the publication
- sleep before publishing (give it 30 seconds to process all the files before publishing)
- checksum validation on the files to confirm not re-pushing unchanged files (lighten the load on dataverse and remove a whole load of 400 duplicate file errors)

**Comment by seabbs** [comment]
Nice all seem like sensible changes and good to protect against future issues in their end.
