### ISSUE TITLE
India not updating. 

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#117]
Looks like india is no longer updating. Would be good to know if this is data related or a run time issue. It doesn't look like it is updating the status.csv.

**Comment by joeHickson** [comment]
20-10-26 08:51:06 INFO Getting regional data
2020-10-26 08:51:07 WARN simpleWarning in gsub("~m", msg, message, fixed = TRUE): argument 'replacement' has length > 1 and only the first element will be used

**Comment by joeHickson** [comment]
looks like it is legitimately broken

**Comment by seabbs** [comment]
hmm is the warning here a broken log of some kind?
