### ISSUE TITLE
ftry and tryCatch

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#118]
To my surprise it looks like `ftry` is not a drop in for `tryCatch` etc and still returns the error unmuffled (so causing a crash). This could be potentially causing some of the knock impacts in the code if you were all as confused as I was (perhaps this was always obvious!).

**Comment by joeHickson** [comment]
I had picked up on that - it annoyingly doesn't seem to have the `silent=TRUE` option so I have ended up doing
`try(futile.logger::ftry(...),silent=TRUE) ` in a few places!

**Comment by joeHickson** [comment]
Perhaps it's time to be a good netizen and fork a PR for the enhancement... https://github.com/zatonovo/futile.logger/pull/96/files
