### ISSUE TITLE
United Kingdom deaths not updating

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#124]
Looks like deaths data in the United kingdom hasn't updated for the last 7 days according to status.csv. This is without a flagged attempt so I would guess either there is a data issue?

**Comment by joeHickson** [comment]
I am debugging - I have spotted I was getting a warning from tripping up testing if a list is.na and fixing that seems to have triggered it to run...  Very strange, particularly given cocin_onset_to_death_delay hasn't changed and that's the only one that's prespecified for uk deaths.

**Comment by seabbs** [comment]
Hmm not sure I totally understand why this was happening but good job resolving!

**Comment by joeHickson** [comment]
No idea either - I'll see if it's a legit solution once it finishes it's other runs - it might be a heisenbug...
