### ISSUE TITLE
UK admissions run failure

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#133]
I see https://github.com/epiforecasts/covid-rt-estimates/tree/master/subnational/united-kingdom/admissions/national

but no update to the summary folder or downstream `status.csv`. Some kind of complete model failure? Any info from the logs @joeHickson?

**Comment by joeHickson** [comment]
I'm getting quite a few unable to delete temporary file errors that I haven't seen since switching infra - this seems to have happened to this run - I was already on it :)

**Comment by joeHickson** [comment]
https://r.789695.n4.nabble.com/tempdir-may-be-deleted-during-long-running-R-session-td4732832.html might be the issue - I'll keep looking.

**Comment by joeHickson** [comment]
@seabbs could I get you to jump onto the meeting a bit early so we can talk this one through?

**Comment by joeHickson** [comment]
I think we might be there on this one

**Comment by seabbs** [comment]
Output looks sane to me.
