### ISSUE TITLE
Add collate estimates to README + add download link. 

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#134]
Looks like the collated estimates for the UK are missing from the README. I have been looking at getting the persistent download link to share with users but so far been unable to understand the API sufficently to make this happen. Any ideas @joeHickson - users were still on the latest_summary.csv that is no longer being updated.

**Comment by joeHickson** [comment]
Hi @seabbs 
When you open a file in dataverse the file ID is in the url
![image](https://user-images.githubusercontent.com/8492240/99787594-db64f180-2b17-11eb-99dd-46e586f0e2ec.png)
You then pop the id in the url the others use:
![image](https://user-images.githubusercontent.com/8492240/99787720-018a9180-2b18-11eb-8b9b-16b6711722e8.png)
that should give you a download link to the latest version of that file id in the original upload  file format.
