### ISSUE TITLE
Overnight run failing with "Runtime error in [sublocation]: using 'as.environment(NULL)' is defunct - as.environment, where"

### ISSUE THREAD

**Issue by joeHickson** [epiforecasts/covid-rt-estimates#137]
2020-11-20 05:28:22 INFO Completed regional estimates
2020-11-20 05:28:22 INFO Regions with estimates: 0
2020-11-20 05:28:22 INFO Regions with runtime errors: 6
2020-11-20 05:28:22 INFO Runtime error in Asia : The following elements of 'sflist' do not contain samples: 5. - rstan::sflist2stanfit, 
fit
2020-11-20 05:28:22 INFO Runtime error in Europe : using 'as.environment(NULL)' is defunct - as.environment, where
2020-11-20 05:28:22 INFO Runtime error in Africa : The following elements of 'sflist' do not contain samples: 3. - rstan::sflist2stanfit
, fit
2020-11-20 05:28:22 INFO Runtime error in Americas : using 'as.environment(NULL)' is defunct - as.environment, where
2020-11-20 05:28:22 INFO Runtime error in Oceania : using 'as.environment(NULL)' is defunct - as.environment, where
2020-11-20 05:28:22 INFO Runtime error in Global : using 'as.environment(NULL)' is defunct - as.environment, where

**Comment by seabbs** [comment]
This looks like all models failed everywhere or that the `future = TRUE` argument is failing to deal with failures properly. 

We need to move versions of `EpiNow2` to resolve this.

**Comment by joeHickson** [comment]
funnily enough I'm focusing on trying to debug that and figure out why it's dying at that point in the code but I'm mystified.

**Comment by seabbs** [comment]
can you pull the results of the run (i.e the regional folder) locally and share? Will investigate interactively to see if i can reproduce

**Comment by joeHickson** [comment]
I'll commit them to the branch. Canada is my chosen guineapig dataset.

**Comment by sbfnk** [comment]
This is a new error, right? And it looks like the one we had the other day, which is that a NULL object is accessed as a list.  Just looking at the latest changes with a stab in the dark, could it be that this
https://github.com/epiforecasts/covid-rt-estimates/blob/5945f5fb620525fbcda1eee3f55f5e89a327e2ca/R/update-regional.R#L129
makes `regional_epinow` return a NULL, which this
https://github.com/epiforecasts/covid-rt-estimates/blob/5945f5fb620525fbcda1eee3f55f5e89a327e2ca/R/update-regional.R#L153
then treats as a list?

**Comment by seabbs** [comment]
yes.

**Comment by joeHickson** [comment]
incoming hotfix

**Comment by joeHickson** [comment]
return_timings = TRUE should cause it to return a list with the timings in

**Comment by joeHickson** [comment]
That doesn't look to be the case - the log implies it's happening to every sublocation and is possibly inside the epinow lib. I'm just double checking the testing of #97 to update the epinow library as that might resolve it all

**Comment by sbfnk** [comment]
So you still get the same error with the fix?

**Comment by joeHickson** [comment]
Yes, but I don't get it with the new epinow

**Comment by seabbs** [comment]
The error here is the model crashing either in one chain or all of them across all regions estimated so there is no data. I should have code to protect against a single chain crash but that has proved difficult to test so I am uncertain it is working.  The `1.3.0` has fixed (hopefully) the underlying issue that leads to the model crash (an exception in the log normal CDF calculation) and added another layer of protection to try and overcome issues with a single chain crashing. 

It may be the case that we still see this issue or failing regions in general at which point we should consider not using the parallel future fitting and falling back to rstan parallisation. The downside to that is then edge case chains can cause the whole box to sit doing nothing or a region will have to be completely killed depending on the time out settings. I think we should look into that as it comes up though.  If we can identify crashing regions then going forward I can use the data from them to try and work on improving the future based stan parallisation as an example of the issue would make coding around it much easier.
