### ISSUE TITLE
UK estimates not updated with no status flag

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#152]
Looks like estimates for all UK data sources failed without touching the status flag (and so don't show as an error). 

![Screenshot 2020-12-01 at 09 54 35](https://user-images.githubusercontent.com/20317649/100724847-3b328680-33bb-11eb-8d0c-7f5bc92ce9b7.png)

**Comment by joeHickson** [comment]
2020-12-01 00:01:59 ERROR Error in download.file(nhs_url, destfile = tmp, mode = "wb"): cannot open URL 'https://www.england.nhs.uk/stat
istics/wp-content/uploads/sites/2/2020/12/COVID-19-daily-admissions-and-beds-20201130.xlsx'

2020-12-01 00:01:59 ERROR Error in download.file(nhs_url, destfile = tmp, mode = "wb"): cannot open URL 'https://www.england.nhs.uk/stat
istics/wp-content/uploads/sites/2/2020/12/COVID-19-daily-admissions-and-beds-20201130.xlsx'

2020-12-01 00:01:59 ERROR Error in download.file(nhs_url, destfile = tmp, mode = "wb"): cannot open URL 'https://www.england.nhs.uk/stat
istics/wp-content/uploads/sites/2/2020/12/COVID-19-daily-admissions-and-beds-20201130.xlsx'

**Comment by joeHickson** [comment]
I think I might be able to spot the bug - is the date in the filename -1 day but the file path not the month that corresponds to the file but instead to today? 2020/12 vs 20201130

**Comment by seabbs** [comment]
sorry Joe lost me there... 😄

**Comment by joeHickson** [comment]
the url looks to contain:
uploads/sites/2/<<YEAR>>/<<MONTH>>/COVID-19-daily-admissions-and-beds-<<ISODATEONLY>>.xlsx
I suggest that if that is the case
month = 12 for date = 20201130 is probably incompatible and this bug will resurface on the 1st of every month as date = yesterday but month = today's month
