### ISSUE TITLE
sort csv files

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/covid-rt-estimates#153]
It would be good to sort the csv files by geography and date for easier navigability:
e.g. https://github.com/epiforecasts/covid-rt-estimates/blob/master/subnational/united-states/cases/summary/rt.csv

**Comment by seabbs** [comment]
I think this must be in `EpiNow2`. They were and should still be in that order so that is quite strange. Will take a look.

**Comment by seabbs** [comment]
done in EpiNow2 - update soon come through by tomorrow.
