### ISSUE TITLE
https://epiforecasts.io/covid/ subnational pages down

### ISSUE THREAD

**Issue by ashander** [epiforecasts/covid-rt-estimates#155]
E.g., https://epiforecasts.io/covid/posts/national/united-states/ gives a 404 
![image](https://user-images.githubusercontent.com/510776/101261038-1105ff00-3702-11eb-8d67-90582d4a1ff1.png)

**Comment by seabbs** [comment]
Thanks for opening this @ashander and highlighting the issue.

This should now be resolved. 

Sam
