### ISSUE TITLE
Adding additional subnational estimates. 

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#16]
We are interested in supporting an increased range of subnational estimates. Ideally, contributors will be able to do the majority of the linking work in order for the core team to focus on optimizing the code and theoretical considerations. In order for this to be possible, we need several things. 

1. Whilst we would like to support estimates for as many places as possible it is key that areas with the fewest other resources/greatest need are prioritized. Users should be encouraged to open an issue highlighting the subnational area they would like estimates to be produced for, flag the available data, and outline to what level they are able to contribute towards the necessary integration steps. At this time we are unlikely to be able to provide subnational estimates below the level 1 geographic region. Though we would be happy to support external implementations. 
2. Users need to be linked to [`covidregionaldata`](https://github.com/epiforecasts/covidregionaldata) and in particular the [SMG](https://github.com/epiforecasts/covidregionaldata/blob/master/inst/smg/SMG.md) which outlines the steps required for adding subnational datasets. This step is required in order for us to support estimates.
3. Users need to be provided with documentation on how to add a new subnational estimate to this repo.   
4. Ideally once a new subnational estimate has been added it will be tested with the results explored before entering daily production.

**Comment by joeHickson** [comment]
We will try and tick off task 3 as part of PR #17 as that brings in a new file for defining the regions. This also introduces a "stable" attribute to each location that can be used for adding a new location for test purposes but not including it in any scheduled runs (a mechanism for task 4).

**Comment by seabbs** [comment]
Looks like this is complete to me. Thanks to @joeHickson and @JAllen42 !
