### ISSUE TITLE
India: Rajasthan silently failing.

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#160]
It looks like updating Rajasthan is silently failing with no flag or warning anywhere. This makes me thing that other regions may also be failing with likewise no warning. 

![Screenshot 2020-12-08 at 14 28 08](https://user-images.githubusercontent.com/20317649/101496572-d5697000-3961-11eb-80e1-824077454ec9.png)

**Comment by joeHickson** [comment]
https://github.com/epiforecasts/covid-rt-estimates/blob/master/subnational/india/cases/national/runtimes.csv

It looks like the runtimes are recording 1 in the timings rather than a timeout - the log is showing it timesout in the traces but when it reloads that csv to get the runtimes it is seeing a time of 1 so recording it as a success. I think this is probably originating inside the epinow timing.

```
2020-12-08 08:59:58 INFO Completed regional estimates
2020-12-08 08:59:58 INFO Regions with estimates: 34
2020-12-08 08:59:58 INFO Regions with runtime errors: 1
2020-12-08 08:59:58 INFO Runtime error in Rajasthan : Rajasthan: model fitting was timed out or failed - 
2020-12-08 08:59:58 INFO Saving timings information to : subnational/india/cases/national
```

**Comment by seabbs** [comment]
That is a runtime of 1 minute. This is due to an error and not  a time out hence the 1 minute runtime.

**Comment by joeHickson** [comment]
ahh that's why it's recording a success - I think originally failures returned no runtime.

**Comment by joeHickson** [comment]
Strange - there's no error in the log until +1 hr and 4 seconds when it died with a timeout.

**Comment by seabbs** [comment]
I can't find any mention of it in the log apart from it being initialised. I see lots of fitting issues in general in India though that have not been clear.

**Comment by joeHickson** [comment]
```
2020-12-08 08:29:38 INFO Completed estimates for: Tamil Nadu
2020-12-08 08:59:58 ERROR Rajasthan: model fitting was timed out or failed -        <---------- this is before it starts its summary print of the outcome
2020-12-08 08:59:58 INFO Completed regional estimates  <------------ this is the summary of the outcome
2020-12-08 08:59:58 INFO Regions with estimates: 34
2020-12-08 08:59:58 INFO Regions with runtime errors: 1
2020-12-08 08:59:58 INFO Runtime error in Rajasthan : Rajasthan: model fitting was timed out or failed - <---------- this is the repetition of the problems from the individual jobs
2020-12-08 08:59:58 INFO Saving timings information to : subnational/india/cases/national
```

**Comment by joeHickson** [comment]
I think all the general stan warnings are just background noise when I look at the logs and we are not reporting on them unless we are looking at why a run failed and it's of note

**Comment by seabbs** [comment]
Which is a problem unfortunately as they are pretty crucial for understanding how estimates are working 🙃 .

**Comment by seabbs** [comment]
if this is a time out then it looks like the status needs updating to catch these. I am not clear how the code as implemented in EpiNow2 would give a run time of 1 minute for something that ran for an hour?

**Comment by joeHickson** [comment]
I agree it's very strange

**Comment by joeHickson** [comment]
ok tracking back further - runtime.rds is 1. Hold my coat, I'm going down this rabbit hole!

**Comment by seabbs** [comment]
Look through all of the other estimates this appears to be the only one with with a problem (though I haven't manually checked the global estimates so there might be a problem hiding there).

**Comment by seabbs** [comment]
The data in India is quite problematic so model issues aren't a shock. It would just ideally be easier to find them than by using manual inspection.

**Comment by joeHickson** [comment]
that is really strange. I see what you mean about the failure. It's odd that the timings crash out almost instantly but it keeps the future thread locked until the end. 
The logic for the status / runtimes csv is this:
```R
 if (is.null(outcome[[dataset_name]][[subregion]])) {
        runtime <- -1
        dataset_counts$failures <- dataset_counts$failures + 1
      } else if (is.finite(outcome[[dataset_name]][[subregion]])) {
        runtime <- outcome[[dataset_name]][[subregion]]
        dataset_counts$successes <- dataset_counts$successes + 1
      }else {
        runtime <- 999999
        dataset_counts$timeouts <- dataset_counts$timeouts + 1
      }
```

Failures are expecting no result to be present. I wonder if this changed with the upgrade of epinow.

**Comment by seabbs** [comment]
Small scale example of model fitting alone: https://gist.github.com/seabbs/b61fe9a88a2b5ddf2ebb79242bd0045e

**Comment by seabbs** [comment]
Using linked example code I saw a run time of 40 minutes (note this is using an initial cumulative fit which may slightly speed up fitting). Output is below. In general this data looks extremely smooth which makes me very sceptical.  

![Screenshot 2020-12-08 at 16 38 34](https://user-images.githubusercontent.com/20317649/101513211-d6a39880-3973-11eb-80ac-7867c98f4f61.png)

**Comment by seabbs** [comment]
Evaluating this it looks like the issue may have been in slightly misspecifying the prior on the length scale of the gaussian process (of interest @sbfnk) to be to long an truncated to high (mean of 21 days and lower bound of 7 days by default). Updating to this: `gp_opts(ls_min = 3, ls_max = 28, ls_mean = 14)` gives me a runtime of 10 minutes. 

The only way I can see to test this is to do large scale batch runs and assess runtimes and fitting criteria.
