### ISSUE TITLE
old columns in rt.csv

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/covid-rt-estimates#164]
This still has a mixture of old and new column names - wasn't this solved by a completely re-run?

https://raw.githubusercontent.com/epiforecasts/covid-rt-estimates/master/national/cases/summary/rt.csv

**Comment by seabbs** [comment]
I am not sure a complete rerun happened? 

![Screenshot 2020-12-09 at 12 33 02](https://user-images.githubusercontent.com/20317649/101630349-afec6d00-3a1a-11eb-9e95-b7dd58745a23.png)

**Comment by joeHickson** [comment]
the complete re-run didn't happen previously due to it generally failing. I have kicked that off now globally with a force and refresh.

**Comment by sbfnk** [comment]
Looks solved to me - thanks!
