### ISSUE TITLE
Subnational estimates not updating in list

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#2]
When estimates are run in a list using `bin/update-via-docker.sh` national estimates run without issue. Subnational estimates all hang with 0 CPU usage. 

The docker logs indicate that the code has reached the EpiNow2::epinow function (i.e each region is running). 

I have been unable to reproduce this in R, in bash, or via docker (replacing the docker run command in `bin/update-via-docker.sh` with a Rscript call). 

Any ideas on this issue would be helpful as currently the only blocker to running a full update using EpiNow2.

**Comment by seabbs** [comment]
Fixed in `EpiNow2` by forcing data.table to use 1 core everywhere - found by @sbfnk

**Comment by joeHickson** [comment]
I wonder if this would resolve the same issue I was experiencing in EpiNow[1]? I was starting to explore it being a conflict between different layers of parallelisation but failed to get to any depth of investigation.
