### ISSUE TITLE
Middle East Data sets not updating

### ISSUE THREAD

**Issue by josebsalazar** [epiforecasts/covid-rt-estimates#208]
Data has not updated since 2021-10-23. This also applies to all Middle East counties.

**Comment by StateCenterKid** [comment]
I see the same issue for the US subnational data - stagnant since 22 October
https://raw.githubusercontent.com/epiforecasts/covid-rt-estimates/master/subnational/united-states/cases/summary/rt.csv"

**Comment by sbfnk** [comment]
Closing as duplicate of https://github.com/epiforecasts/covid/issues/180 (now resolved)
