### ISSUE TITLE
Data not updating for 1 week

### ISSUE THREAD

**Issue by StateCenterKid** [epiforecasts/covid-rt-estimates#211]
I've been pulling data from https://github.com/epiforecasts/covid-rt-estimates/blob/master/subnational/united-states/cases/summary/rt.csv and it has not been updated since 27 Feb 2022.   Is this just a temporary delay or has the analysis been discontinued?

**Comment by sbfnk** [comment]
It's a (hopefully) temporary issue we're hoping to fix soon. That said, the regular estimates will soon be discontinued.

**Comment by sbfnk** [comment]
Estimates are back now. Thanks for flagging.
