### ISSUE TITLE
Add global and WHO region estimates. 

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#22]
There is a policy interest in having global /higher than country-level estimates. These can either be implemented in the current case and death scripts or split out into their own processing stage. The best option is likely to split out as higher-level estimates will otherwise dominate the summary plots.

**Comment by joeHickson** [comment]
does this relate to @JAllen42 's work trying to bring cases / deaths into the same processing pattern? https://github.com/epiforecasts/covid-rt-estimates/tree/refactor_national_updates

**Comment by seabbs** [comment]
Yes, potentially. 

Its something I may need to implement in the short term in the current set up (by just calling `regional_epinow` twice on data with different aggregation scales. 

The reason is so that there can be a top-level estimate shown before a region is selected (i.e like [this](https://epiforecasts.io/covid/posts/national/united-kingdom/)). Apparently a headline figure is very useful for those monitoring the global, regional picture. 

I will likely implement a quick version of this today but adding to the refactoring would be great longer term.
