### ISSUE TITLE
NULL messages in the logs

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#24]
Seeing lots of NULL Warnings in logs running using the new script approach. @joeHickson is this expected? 

![Screenshot 2020-09-03 at 10 45 47](https://user-images.githubusercontent.com/20317649/92099750-ce671a80-edd2-11ea-86dd-434bedbcbbcf.png)

Seeing this in all regional estimates but not in national-level estimates indicating to me its probably coming from the new `covid-rt-estimates` implementation. See https://github.com/epiforecasts/covid-rt-estimates/tree/estimate-test for a partial run using settings from the master (will complete as and when estimates are done).

**Comment by joeHickson** [comment]
I think this might be fixed by the epinow2 changes going in to log warnings internally and stop them propagating but I'll take a look

**Comment by joeHickson** [comment]
![image](https://user-images.githubusercontent.com/8492240/92110919-64a33c80-ede3-11ea-9bb8-e15fe8e6878f.png)
^ germany run with latest rt and #63 epinow2

I think I might be safe to blame this one on epiforecasts/EpiNow2#63

**Comment by joeHickson** [comment]
If it is what I think then cnd_muffle might be the answer - the warning was bubbling but it seemed the content was being processed by the inner handler and not passed up the stack. Stopping the warning propagation in the handlers looks like it may have been the fix.

**Comment by seabbs** [comment]
Awesome - I've just checked and it is resolved. Thanks for reviewing.
