### ISSUE TITLE
Capture R errors

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#29]
The logging is very useful but when an issue occurs that doesn't have a built-in logging message then there is no feedback as to why this may have occurred. Obviously one option would be to add logging messages for all possible issues but this will end up being essentially a rewrite of R's own warning/error system. Given this, it might be a good idea to set up console sinking to a separate logging file (https://stackoverflow.com/questions/11666086/output-error-warning-log-txt-file-when-running-r-script-under-command-line) as a secondary debug tool.

**Comment by joeHickson** [comment]
Hi @seabbs , do you have an example of these? we should be getting the warning / errors caught into the logs from the run-regional and once the global switch over that should do likewise.

**Comment by seabbs** [comment]
From the script that launches EpiNow2? This was happening when I was hacking around with the global level estimates so perhaps will also be resolved when switch over to the new format?

**Comment by joeHickson** [comment]
yes, the global levels don't yet go through the same error handling.

https://github.com/epiforecasts/covid-rt-estimates/blob/master/R/run-region-updates.R#L59 should give you an idea of what we have done so far:

WithCallingHandlers get triggered in the call stack at the point of the error.
Warnings can then continue without breaking (which happens with try/catch loop catching warnings) and the muffle command stops them propogating to other handlers. This *could* have the trace added but could get very noisy! Perhaps we could add it to log the stack trace at "trace" debug level
Errors log the stack trace location using this (so the trace is from the correct point in the call stack) then bubble to the error handler in the try/catch
Try catch has the error bubble up to it and handles logging and continuing.

It's slightly cumbersome to need the three prongs but it seems to cover off all the scenarios. It's annoying that the error object in R doesn't contain the triggering trace so you have to dump it yourself!

**Comment by seabbs** [comment]
ah okay that all sounds sensible. Thanks!
