### ISSUE TITLE
Cases and deaths still failing. 

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#38]
The new implementation of global cases and deaths fails for all scales (national and regional). 

I see variants of the following error tree: 

```
WARN [2020-09-15 00:05:56] cases: NULL - mccollect, jobs, TRUE
ERROR [2020-09-15 00:05:56]      █
ERROR [2020-09-15 00:05:56]   1. ├─base::tryCatch(...)
ERROR [2020-09-15 00:05:56]   2. │ └─base:::tryCatchList(expr, classes, parentenv, handlers)
ERROR [2020-09-15 00:05:56]   3. │   └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
ERROR [2020-09-15 00:05:56]   4. │     └─base:::doTryCatch(return(expr), name, parentenv, handler)
ERROR [2020-09-15 00:05:56]   5. ├─base::withCallingHandlers(...)
ERROR [2020-09-15 00:05:56]   6. ├─global::run_regional_updates(datasets = datasets, args = args)
ERROR [2020-09-15 00:05:56]   7. │ └─global::rru_process_locations(datasets, args, excludes, includes)
ERROR [2020-09-15 00:05:56]   6. ├─global::run_regional_updates(datasets = datasets, args = args)
ERROR [2020-09-15 00:05:56]   7. │ └─global::rru_process_locations(datasets, args, excludes, includes)
ERROR [2020-09-15 00:05:56]   8. │   ├─base::tryCatch(...)
ERROR [2020-09-15 00:05:56]   9. │   │ └─base:::tryCatchList(expr, classes, parentenv, handlers)
ERROR [2020-09-15 00:05:56]  10. │   │   └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
ERROR [2020-09-15 00:05:56]  11. │   │     └─base:::doTryCatch(return(expr), name, parentenv, handler)
ERROR [2020-09-15 00:05:56]  12. │   ├─base::withCallingHandlers(...)
ERROR [2020-09-15 00:05:56]  13. │   └─global::update_regional(...)
ERROR [2020-09-15 00:05:56]  14. │     └─EpiNow2::regional_epinow(...)
ERROR [2020-09-15 00:05:56]  15. │       └─future.apply::future_lapply(...)
ERROR [2020-09-15 00:05:56]  16. │         └─future.apply:::future_xapply(...)
ERROR [2020-09-15 00:05:56]  17. │           └─future::future(...)
ERROR [2020-09-15 00:05:56]  18. │             └─future:::makeFuture(...)
ERROR [2020-09-15 00:05:56]  19. │               └─future:::fun(...)
ERROR [2020-09-15 00:05:56]  20. │                 ├─future::run(future)
ERROR [2020-09-15 00:05:56]  21. │                 └─future:::run.MulticoreFuture(future)
ERROR [2020-09-15 00:05:56]  22. │                   └─future:::requestCore(...)
ERROR [2020-09-15 00:05:56]  23. │                     └─future:::usedCores()
ERROR [2020-09-15 00:05:56]  24. │                       └─future:::FutureRegistry(reg, action = "list", earlySignal = TRUE)
ERROR [2020-09-15 00:05:56]  25. │                         └─future:::collectValues(where, futures = futures[idxs], firstOnly = FALSE)
ERROR [2020-09-15 00:05:56]  26. │                           ├─future::resolved(future, run = FALSE)
ERROR [2020-09-15 00:05:56]  27. │                           └─future:::resolved.MulticoreFuture(future, run = FALSE)
ERROR [2020-09-15 00:05:56]  28. │                             └─future:::signalEarly(x, ...)
ERROR [2020-09-15 00:05:56]  29. │                               ├─future::result(future)
ERROR [2020-09-15 00:05:56]  30. │                               └─future:::result.MulticoreFuture(future)
ERROR [2020-09-15 00:05:56]  31. │                                 └─future:::FutureRegistry(...)
ERROR [2020-09-15 00:05:56]  32. │                                   └─future:::collectValues(where, futures = futures[idxs], firstOnly = FALSE)
ERROR [2020-09-15 00:05:56]  33. │                                     ├─future::resolved(future, run = FALSE)
ERROR [2020-09-15 00:05:56]  34. │                                     └─future:::resolved.MulticoreFuture(future, run = FALSE)
ERROR [2020-09-15 00:05:56]  35. │                                       └─future:::signalEarly(x, ...)
ERROR [2020-09-15 00:05:56]  36. │                                         ├─future::result(future)
ERROR [2020-09-15 00:05:56]  37. │                                         └─future:::result.MulticoreFuture(future)
ERROR [2020-09-15 00:05:56]  38. │                                           └─base::stop(ex)
ERROR [2020-09-15 00:05:56]  39. └─(function (e) ...
ERROR [2020-09-15 00:05:56] cases: Failed to retrieve the result of MulticoreFuture (future_lapply-72) from the forked worker (on localhost; PID 1620). Post-mortem diagnostic: No process exists with this PID, i.e. the forked localhost worker is no longer alive. -
WARN [2020-09-15 00:05:56] simpleWarning in outcome[[location$name]]$start <- start: Coercing LHS to a list
```

**Comment by seabbs** [comment]
@joeHickson any ideas?

**Comment by joeHickson** [comment]
I have seen that message when the R worker thread gets killed off (only ever at my bidding with a `kill 0000` to stop a runaway thread). Let me give it a spin. How long did the failure take?

**Comment by seabbs** [comment]
[info.log](https://github.com/epiforecasts/covid-rt-estimates/files/5223438/info.log)


Here is the log (cutting out the successful subnational estimates). Falls over after a few minutes for the first failure and then more rapidly. I agree that is the likely issue but as this was previously working I think the changes have introduced a problematic factor. You can see this sort of problem if you run out of RAM or disk space as well (the disk on this server seems fine).

**Comment by joeHickson** [comment]
Thanks @seabbs - that looks to be failing very quickly. Mine's still running so I'll see if I can reproduce it. Ram doesn't look like a problem on mine - currently 13.1 / 252G

**Comment by seabbs** [comment]
Did you run starting with all the subnational estimates? It may be related to #25 which I think is due to RAM not be released properly when trying to sequentially run multiple processes in a single R script.

**Comment by joeHickson** [comment]
No, just the specific location. I'll give a full batch run a go.

**Comment by seabbs** [comment]
The server I have been running on has 126Gb of RAM so if each estimate uses around 10 ~ 15 Gb of RAM then it would make sense that issues appear after 10 or so estimates. If your box has 256Gb of RAM it may well be able to brute force it's way through this issue for now which would be good as the deaths Rt estimates are now a week out of date so could really do with an update.

**Comment by joeHickson** [comment]
Mine looked to grow and shrink but I'll see once it runs a full suite.

**Comment by seabbs** [comment]
Well done getting the automated update sorted @joeHickson. I am seeing some missing estimates for national/cases but nothing too bad. natioanl/deaths and region/cases + region/deaths seem like they are being problematic though?

**Comment by joeHickson** [comment]
It looks like they just haven't been added to the git repo yet.
![image](https://user-images.githubusercontent.com/8492240/93376018-e6b64b00-f850-11ea-9cec-9f6736f9392b.png)

**Comment by joeHickson** [comment]
I see what you mean about the national deaths - I'll have a deeper dig in the morning

**Comment by joeHickson** [comment]
it processed this run - I committed all the national data and left it running on the rest. I'll keep an eye on that.

**Comment by seabbs** [comment]
So it looks like cases and deaths are now up to date but regional estimates are a problem (https://epiforecasts.io/covid/posts/global/) with only an estimate for Europe available. 

I see the new issue flagging problem areas (#42) but can the logs be pushed somewhere (or some other summary metric) to allow me to keep track of your updates more easily than going through the GitHub to look at pushed locations?

**Comment by joeHickson** [comment]
you can get the summary from the runtimes.csv file in the root if that helps?

**Comment by seabbs** [comment]
As far as I can tell it doesn't show anything for deaths, or regional estimates in general? Potentially due to some upstream failure?

**Comment by joeHickson** [comment]
I think that's because it wasn't returning the data. I'm currently running belgium with higher timeouts then those regional estimates are next on my hit list.

**Comment by joeHickson** [comment]
region/deaths is there from this latest run but it's outputting in region/deaths/national which is definitely a bug. 
I have kicked off region/cases and will see what's there when I get back from lunch.
The deaths is now showing in the timings - I think there was an issue where the regional data sets were not requesting a return_timings from epinow2 which will hopefully resolve it (hotfix this week with they typo on the epinow2 call for return_timings and all_regions_summary )

**Comment by seabbs** [comment]
Ah right all makes sense - good stuff!

**Comment by seabbs** [comment]
Still seeing only Europe in the latest region outputs. Is this a timeout issue or something else?

**Comment by seabbs** [comment]
Resolved by updates from @joeHickson and epiforecasts/EpiNow2#73
