### ISSUE TITLE
Specify root path for data output

### ISSUE THREAD

**Issue by joeHickson** [epiforecasts/covid-rt-estimates#41]
blocks #9 
Specifying the root path allows for shifting the data output into a scratch location away from the git checkout. This location will then be used to publish the data out elsewhere.

Currently this will default to the existing location but potentially this should shift to default to ./data/generated and be added to the gitignore. This final move would also suggest shuffling the current .rds files from ./data to ./data/source or ./data/reference to help keep the data folder tidy.

**Comment by joeHickson** [comment]
Update - renamed ticket

I think this could be as simple as using ./data/tmp as the working directory for the data.
Create this as an optional argument (Defaulting to false), moving the .rds files into data/reference and adding data/tmp to the git ignore.
#9 can then use this flag
Once we are publishing to a new location we can remove the flag all together or (less desirable) leave it in but change the default (major version change - existing users would no longer get data in the current folder structures). <- this can be directed based on how many people are using this. We will be removing the data from within the github project but for those generating their own results locally do they depend on the output location for future scripts?

**Comment by seabbs** [comment]
All seems like good ideas :+1:
