### ISSUE TITLE
Current problem locations

### ISSUE THREAD

**Issue by joeHickson** [epiforecasts/covid-rt-estimates#42]
Starting a ticket to highlight problem locations that are having issues (from runtimes.csv)

Timeouts:
dataset	subregion	start_date	runtime
belgium	Brussels	15/09/2020 16:13	999999
belgium	Flanders	15/09/2020 16:13	999999
belgium	Unknown	15/09/2020 16:13	999999
belgium	Wallonia	15/09/2020 16:13	999999
brazil	SÃ£o Paulo	15/09/2020 16:31	999999
canada	New Brunswick	15/09/2020 18:33	999999
germany	Baden-WÃ¼rttemberg	15/09/2020 20:58	999999
india	Manipur	15/09/2020 22:10	999999
italy	Lombardia	17/09/2020 05:58	999999
italy	Trentino-Alto Adige	17/09/2020 05:58	999999
united-kingdom	East Midlands	17/09/2020 07:59	999999
united-kingdom	North West	17/09/2020 07:59	999999
united-kingdom	Yorkshire and The Humber	17/09/2020 07:59	999999

I'm re-running Belgium  now to see if it's still an issue

**Comment by seabbs** [comment]
What is the timeout currently set at and are these true across all multiple runs?

**Comment by seabbs** [comment]
Think these have mostly been resolved by epiforecasts/EpiNow2#74
