### ISSUE TITLE
Increase time out in the UK

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#44]
The UK case data is problematic at the moment due to the underlying increase in cases and the breakdown of reliable testing data. This instability increases the difficulty of fitting the model. Given this, it looks like the timeout needs to be increased in order to provide estimates

**Comment by seabbs** [comment]
In the current set up I think this needs to be done across all estimates at once. Potentially this is a case for moving this to the R6 object and out of the command line (perhaps with a command line override).

**Comment by joeHickson** [comment]
I agree about the issue - I'm noticing the same for belgium. It will go away once we hit new infrastructure and can remove the timeout but that's too far down the line! My concern with including it in the dataset list is that is currently processing platform agnostic - timeouts are specific to a processing platform. Perhaps it needs a shadow list in the infra project?

**Comment by seabbs** [comment]
Hmm makes sense. Yes sounds like it makes sense.

**Comment by seabbs** [comment]
Should be resolved by epiforecasts/EpiNow2#74
