### ISSUE TITLE
Summary not generated due to a gsub error.

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#47]
See server logs for details of the error. 

I have sidestepped this for now by adding a `tryCatch` call to `regional_epinow` which ensures that `regional_summary` always gets called. 

I have been unable to reproduce this anywhere but the production server and have not been able to inspect the line number that is causing the error on the production server. Manual inspection of the code (both here and in `EpiNow2` does not shed any light).

**Comment by seabbs** [comment]
Exploring this locally this was because some timed out regions did not have a newly added summary column. This only showed as an issue when they were first in the list.

**Comment by joeHickson** [comment]
It might be that epinow2 protects the summary with this to ensure it only calls the summary if it has a bundle of results to hand it:

```
sucessful_regional_out <- purrr::keep(purrr::compact(regional_out), ~is.finite(.$timing))
  # only attempt the summary if there are at least some results
  if (summary && length(sucessful_regional_out) > 0) {
```

**Comment by joeHickson** [comment]
I have just remembered where I have seen the gsub issue before - when it's handed an object to the logging library and it has tried to do string substitution on it. It causes an error to be thrown on the error handling so you lose the underlying problem!

**Comment by seabbs** [comment]
Yes that makes sense.
