### ISSUE TITLE
Death to report

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#53]
This delay needs to be updated based on literature/public estimates. @kathsherratt do you have any ideas on this? When I checked the line-list I saw just 6 observations with complete data.

**Comment by kathsherratt** [comment]
This is a quick summary of what's in the international public linelist.

![image](https://user-images.githubusercontent.com/62290797/94570455-c6ca5280-0266-11eb-96e1-39886007ecbd.png)
- Onset to death = total time in days, symptom onset to date of death. 
- Onset to admission = days from admission to hospital to death. (Sometimes the only measure available.)


I will also have a look through the literature. From a first search, there seems to be relatively little on onset to death (compared to estimates of onset to report or admission), but maybe a handful of papers we could use.

**Comment by joeHickson** [comment]
Those numbers look a bit questionable - I would have expected onset->death to be greater and statistically different from admission->death.

**Comment by kathsherratt** [comment]
My bad - thanks @joeHickson . Updated the table.

**Comment by seabbs** [comment]
It's a shame the coverage across countries is so poor. I don't think we can really use these are generalizable estimates, unfortunately. Will have a look for another data source but I haven't seen anything.

**Comment by sbfnk** [comment]
I'm aware of two public estimates:

[ONS](https://www.gov.uk/government/publications/note-on-reporting-of-deaths-involving-covid-19-7-april-2020) say "the median time from death to reporting is 3 days (England)" which seems plausible.

[CDC](https://www.cdc.gov/coronavirus/2019-ncov/hcp/planning-scenarios.html#table-2) say it takes a median of 19-21 days which seems very long indeed.

**Comment by sbfnk** [comment]
There's also this from https://www.medrxiv.org/content/10.1101/2020.06.17.20133983v1 which looks closer to the ONS estimate though it's not obvious where this is from in ref 21.

<img width="700" alt="image" src="https://user-images.githubusercontent.com/1156307/94781815-44ef3c00-03c2-11eb-9a73-7a639a093ad2.png">

**Comment by seabbs** [comment]
Ping @kathsherratt @sbfnk - this is unresolved but closing.
