### ISSUE TITLE
Saved dated copies of each summary folder

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#55]
Whilst it would be nice to be able to store full samples from each region it may be more practical in the short term to instead save the summarised estimates available in each summary folder. This can either be linked to #9 or be a git only implementation based on copying the summary folder (or just the csv's it contains into a dated folder for each region).   

If a git based intervention then summarised results could be stored in a `covid-rt-estimates-archive` repo for example in order to avoid additional history bloat and provide a repo that is easier for others to download (as it won't contain the history of samples and hence will be much smaller even with several hundred archived csv's).

**Comment by joeHickson** [comment]
This will be resolved by #9 and #101
