### ISSUE TITLE
New summary table for status overview

### ISSUE THREAD

**Issue by joeHickson** [epiforecasts/covid-rt-estimates#57]
In run-regional-updates handle a new csv (status.csv?) that contains the latest summary for each location when processing the run outcome. This may also help with #54 .

Perhaps the following columns:
| Dataset | subregion | last run timestamp | last run status | latest results generated at | latest results data up to |
| -------- | ----------- | --------------------- | --------------- | ----------------------------- | -------------------------- |
| united-kingdom | * | 2020-09-30 13:45:53 | No New Data Available | 2020-09-29 05:34:23 | 2020-09-25 |
| united-kingdom | London | 2020-09-30 13:45:53 | No New Data Available | 2020-09-29 05:34:23 | 2020-09-25 |

last run status = Success | Error | Timed Out | No New Data Available (I think we should be able to detect all these conditions)

**Comment by joeHickson** [comment]
@seabbs how's this for a starter?

**Comment by seabbs** [comment]
Yes looks really good. Would the idea be to just have a row per dataset (so uk-cases, usa-cases etc.)? Can see it getting very crowded if it also has info on each subregion? 

It would be great to have a count of the number of regions timed out/erroring etc as well.

**Comment by joeHickson** [comment]
I can see the overwhelming problem. Do we care about an easy summary of each sublocation or is it the stats for the last run that matter? We will still have the detailed log in the timings csv.
e.g. columns:
| Dataset | last attempted at timestamp | last attempt status | latest results generated at | l.r. data up to | l.r. successful regions | l.r. timing out regions  | l.r. erroring regions |
| -------- | ----------- | --------------------- | --------------- | ----------------------------- | -------------------------- | ------- | ---- | ---- |
| united-kingdom  | 2020-09-30 13:45:53 | No New Data Available | 2020-09-29 05:34:23 | 2020-09-25 | 9 | 2 | 0 |
| united-kingdom  | 2020-09-30 13:45:53 | No New Data Available | 2020-09-29 05:34:23 | 2020-09-25 | 9 | 2 | 0 |

Alternatively we could accept that it is a big file but ensure it is sorted sensibly (e.g. by dataset then region) so that it can be skimmed by human eye if needed but rely on later filtering to display a subset on appropriate web pages (e.g. only region = * on a summary status page)?

**Comment by seabbs** [comment]
I think I like this proposed set up. We could have another one for sublocations at a later date but this definitely does the job. Could also maybe add a list of which regions error/timed out potentially as additional information but not necessarily.

**Comment by seabbs** [comment]
Adding a column with the date of the last complete update (so the minimum date across all sublocations) would be really great as well. That would let us ping an issue if an estimate for any region in the UK for example gets more than say a week out of date.

**Comment by joeHickson** [comment]
| Dataset | last attempted | last attempt status | latest results | l.r. status |  l.r. data up to | l.r. successful regions | l.r. timing out regions  | l.r. erroring regions | last complete |
| -------- | ----------- | --------------------- | --------------- | ----------------------------- | -------------------------- | -- | ----- | ---- | 
| united-kingdom  | 2020-09-30 13:45:53 | No New Data Available | 2020-09-29 05:34:23 | Partial Completion | 2020-09-25 | 9 | 2 | 0 | 2020-09-17 06:23:12 |
| russia  | 2020-09-30 18:51:22 | Partial Completion | 2020-09-30 18:51:22 | Partial Completion | 2020-09-27 | 11 | 7 | 0 | N/A |

**Comment by seabbs** [comment]
Like it. Is last completely successful here when all regions succeeded in a single run or most recent date that all regions were successful at least? Sorry a little vague. What I mean is that for the second one you could never have all regions succeeding in a single run but you could still have a date when all estimates were available as all regions might have succeeded across multiple runs?

**Comment by joeHickson** [comment]
I was thinking last completely successful run but I can see the thought of being the oldest region result. I can generate the former from the existing logging, the latter would need to analyse the results.

I guess the purpose is to inform us when we need to manually run with longer timeouts due to issues so oldest result set is probably more helpful?

**Comment by seabbs** [comment]
yes exactly. They are both useful pieces of info but if we except some level of failure then we need to know at what point its getting out of hand and changes are needed.

**Comment by joeHickson** [comment]
data.frame(
      dataset = character(),
      last_attempt = POSIXct(),
      last_attempt_status = character(),
      latest_results = POSIXct(),
      latest_results_status = character(),
      latest_results_data_up_to = Date(),
      latest_results_successful_regions = integer(),
      latest_results_timing_out_regions = integer(),
      latest_results_failing_regions = integer(),
      oldest_region_results = POSIXct(),
    )

How is this for ambiguity on the naming? Ideally oldest_region_results == latest_results but will vary at hour / minute level due to differences in when the time is captured (e.g. start / end of run or file date) but it should be close enough

**Comment by seabbs** [comment]
yes - looks really good.
