### ISSUE TITLE
csv output from new UK data sources

### ISSUE THREAD

**Issue by kathsherratt** [epiforecasts/covid-rt-estimates#63]
Linked to #62 , adding new data sources for UK estimates.

For these to be used, ideally the summary of Rt estimates needs to be output in a single csv file. 

This should
 - Combine Rt estimates from each data source 
 - Include a data source identifier
 - Filter the `type` variable to only the Rt "estimates" (not the estimates from partial data or forecasts)
 - Save in a csv in a dedicated folder within the `united-kingdom` folder.

Below is example code to get to what is needed. In this example the new dedicated folder for output is called "all-summary-rt".

However I am not sure where this needs to go to get it running in the process after the daily Rt estimates have finished. 

```
# Get Rt estimates summary from each data source
cases <- fread(here::here("subnational", "united-kingdom", "cases", "summary", "rt.csv"))
cases <- cases[cases$type == "estimate"][, data_source := "test-positive cases"]

deaths <- fread(here::here("subnational", "united-kingdom", "deaths", "summary", "rt.csv"))
deaths <- deaths[deaths$type == "estimate"][, data_source := "deaths"]

admissions <- fread(here::here("subnational", "united-kingdom", "admissions", "summary", "rt.csv"))
admissions <- admissions[admissions$type == "estimate"][, data_source := "hospital admissions"]

# Bind all data sources
uk_rt <- data.table::rbindlist(list(cases, deaths, admissions),
                               fill = TRUE, use.names = TRUE)

# Save back to main UK folder
write.csv(uk_rt, here::here("subnational", "united-kingdom", "all-summary-rt", paste0(Sys.Date(), "-uk-rt.csv"))
```

**Comment by seabbs** [comment]
Hi @kathsherratt, 

This all seems pretty sensible and I think controlling the end product here explicitly is quite important. I might like to call the target folder `summary` as we can then put other things in it at a later date potentially. I would also suggest using an rt folder in that and adding dated csvs to it rather than adding the dated csv's directly. 

@joeHickson for these sort of ad-hoc jobs that don't fit the general infrastructure does it make sense to just set up a daily CRON job to take whatever is sitting in the target folders and produce this?

**Comment by joeHickson** [comment]
I was contemplating this earlier - the raw sets of results are valid and good but re-assembling them would be helpful. I can see this possibly applying to multiple datasets at summary and also at subregion level.

**Comment by seabbs** [comment]
yes, agree.

**Comment by joeHickson** [comment]
one option is to say this is a publication task and bundle it with website but equally I could be tempted to add a new function here:
https://github.com/epiforecasts/covid-rt-estimates/blob/master/R/run-region-updates.R#L31

something like "collate variants" that takes any multi-subfolder (e.g. /cases/ + /deaths/ ) and brings them together into a /collated/ variant. It could run at the end of every loop and we rely on github to go "no change" to the folders most of the time.

something like
x/cases/...
x/deaths/...

goes to 
x/collated/summary with cols cases, deaths copied from the path naming?

**Comment by joeHickson** [comment]
so my thought is you would have:

united-kingdom/cases/national/<>/data
united-kingdom/deaths/national/<>/data
united-kingdom/collated/national/<>/data
and
united-kingdom/cases/summary/<>/data
united-kingdom/deaths/summary/<>/data
united-kingdom/collated/summary/<>/data

effectively causing the collated results to appear as a separate set of results

**Comment by joeHickson** [comment]
this could also apply to the national / region folders to give you collated deaths / cases.

so collate national/<type>/..., region/<type>/...  and  subnational/*/<type>, only collating where count(unique(type[excluding "collated"])) > 1

perhaps just putting the hardcoded option in as a quick fix is the short term solution? scanning the directories and looping through shouldn't be too difficult but it will take a bit of fiddling to get the collation correct.

**Comment by seabbs** [comment]
yes, I think hard coding for now and expanding later would be a good idea. Providing some kind of all estimate summary csv would no doubt be sensible.

**Comment by kathsherratt** [comment]
Thanks both. I'll have a go writing this as an independent function and stick it in a PR for edits as needed.

**Comment by seabbs** [comment]
This is now in place in the form of a function but needs to be linked up to the infrastructure.

**Comment by joeHickson** [comment]
As discussed in the conference call we will use a test if united-kingdom-admissions is in the include list to trigger the function after it's processed the data
https://github.com/epiforecasts/covid-rt-estimates/blob/master/R/run-region-updates.R#L31

```R
if("united-kingdom-admissions" %in% includes){
   callSamsFunction()
}
```

Whilst a bit nasty we know this will be the last data set to be processed for the uk and our current production environment triggers each in turn.

This will need changing when we move to parallel machines for data processing

**Comment by seabbs** [comment]
Sounds spot on. Call should be:

```
collate_estimates(name = "united-kingdom", target = "rt")
```

If you have a local version of this running or access to the server giving this a manual run today and publishing the estimates would be a useful test.

**Comment by joeHickson** [comment]
@seabbs is there a branch for that?

**Comment by seabbs** [comment]
@kathsherratt  PR'd and I reviewed it so it's in master (in `R/utils.R`) but uncalled.

**Comment by seabbs** [comment]
@joeHickson any idea on a timeline for this to start being scheduled or ideas on actions I can take on our end to get this output?

**Comment by joeHickson** [comment]
just starting it now

**Comment by seabbs** [comment]
aweosme!

**Comment by joeHickson** [comment]
Error in data.table::fwrite(df, here::here("subnational", name, "collated",  : 
  No such file or directory: '/home/covid/subnational/united-kingdom/collated/rt/2020-10-08.csv'. Unable to create new file for writing (it does not exist already). Do you have permission to
 write here, is there space on the disk and does the path exist?
Calls: run_regional_updates -> collate_estimates -> <Anonymous>
In addition: Warning messages:
1: In storage.mode(default) <- type :
  NAs introduced by coercion to integer range
2: In dir.create(here::here("subnational", name, "collated", target)) :
  cannot create dir '/home/covid/subnational/united-kingdom/collated/rt', reason 'No such file or directory'

**Comment by seabbs** [comment]
sounds like it needs a `recursive = TRUE` set. One sec.

**Comment by joeHickson** [comment]
I'll pop that in now

**Comment by seabbs** [comment]
Done here #68 but may be faster to do elsewhere.

**Comment by joeHickson** [comment]
ok it's in but being ignored because I think it's tripping up the git ignore date filter
