### ISSUE TITLE
Brazil last updated 7 days ago.

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#74]
Any information in the logs as to why this might be @joeHickson?

**Comment by kathsherratt** [comment]
Looks like data last updated 2020-10-03 (so could be a "data hasn't changed since last run" error). I'm checking for the issue in `covidregionaldata` now.

**Comment by kathsherratt** [comment]
Fixed in [PR#82](https://github.com/epiforecasts/covidregionaldata/pull/82) to` covidregionaldata`, so this will update when that PR is merged.

**Comment by seabbs** [comment]
Will close this once a new update winds its way through 😄
