### ISSUE TITLE
Old and new regions for cases presents in estimates - UK

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#76]
@kathsherratt could you flag the old depreciated UK regions that we should remove from the repository. At the moment they are shown on the website and in all downstream CSVs. 

@joeHickson I think the best solution to this is to delete the folders for these regions in order to stop them appearing in the summaries.

**Comment by kathsherratt** [comment]
Thanks for noticing this Sam, sorry I missed it.

For cases, deaths, and admissions, we need to remove:
- [Yorkshire and The Humber](https://github.com/epiforecasts/covid-rt-estimates/tree/master/subnational/united-kingdom/cases/national/Yorkshire%20and%20The%20Humber)
- [North East](https://github.com/epiforecasts/covid-rt-estimates/tree/master/subnational/united-kingdom/cases/national/North%20East)
- [West Midlands](https://github.com/epiforecasts/covid-rt-estimates/tree/master/subnational/united-kingdom/cases/national/West%20Midlands)
- [East Midlands](https://github.com/epiforecasts/covid-rt-estimates/tree/master/subnational/united-kingdom/cases/national/East%20Midlands)

For admissions only, we need to remove:
- [United Kingdom](https://github.com/epiforecasts/covid-rt-estimates/tree/master/subnational/united-kingdom/admissions/national/United%20Kingdom)

**Comment by seabbs** [comment]
This is getting fairly urgent. Can anyone look at this please? 

I see multiple regions being updated for deaths in a way that I don't understand: 

https://github.com/epiforecasts/covid-rt-estimates/tree/master/subnational/united-kingdom/deaths/national

@kathsherratt are there duplicate regions in the data source? 

I have removed the UK for admissions.

**Comment by joeHickson** [comment]
Certainly the list at the point it's passed to epinow 2 is different:
```
2020-10-14 01:01:11 INFO Producing estimates for: East of England, England, London, Midlands, North East and Yorkshire, North West, Northern Ireland, Scotland, South East, South West, Wales, United Kingdom
2020-10-15 00:59:27 INFO Producing estimates for: East Midlands, East of England, England, London, North East, North West, Northern Ireland, Scotland, South East, South West, Wales, West Midlands, Yorkshire and The Humber, United Kingdom
```
We don't have logging of what locations were in the original data.

**Comment by joeHickson** [comment]
Is it possible the data source has changed?

**Comment by kathsherratt** [comment]
The data source seems fine, returning the correct geographies (4 nations + 7 NHS regions) with data present for the correct variables (`cases_new`, `deaths_new`, and `hosp_new_blend`).
```
data <- covidregionaldata::get_regional_data("uk", nhsregions = TRUE)
unique(data$region)
```

But it does look like the regions that are only brought in by using the `nhsregion = TRUE` argument (Midlands; North East & Yorkshire) haven't updated recently, at least for cases ([last updated](https://github.com/epiforecasts/covid-rt-estimates/tree/master/subnational/united-kingdom/cases/national) 2 days ago).

Has anything changed with the use of `data_args` in `dataset-list.R`? Could it be a change where the argument `nhsregions = TRUE` doesn't get passed through to `covidregionaldata`?

**Comment by joeHickson** [comment]
let see if that reoslves it

**Comment by joeHickson** [comment]
looks like some more bits might have gone astray with the problematic merge of #73
