### ISSUE TITLE
Ability to specify a subset of countries/regions to update

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#8]
It would be great to be able to specify a subset of regions to update. This would make it easier to split processing across multiple compute nodes in a fairly simple fashion.

**Comment by joeHickson** [comment]
This sounds like a good one for us to look at

**Comment by joeHickson** [comment]
Working on this one over here - https://github.com/epiforecasts/covid-rt-estimates/blob/i8_location_control/R/run_region_updates.R
Work in progress.
This gives a CLI interface to the run_region_updates script - it will parse the arguments handed to it and allow you to include / exclude data sets individually or as a list. It also exposes control for verbosity and log location.

Rscript R/run_region_updates.R [-[v|w|q]] [--log logfile_location] [-[e|i|-[in|ex]clude <region list>
with <region list> in the format united-states/texas,united-states/florida or germany/*,belgium/*,italy/*

e.g.

Rscript R/run_region_updates.R -w -i united-states/texas,united-kingdom/*
-> Run in extra verbose mode, only for texas and all uk subregions

**Comment by seabbs** [comment]
Looks good so far! I particularly like the region_list for storing individual region settings.

**Comment by joeHickson** [comment]
Hopefully it should be super fast to add additional regions to process - once you have the data source hooked into covidregionaldata just drop it in the list and away you go!
