### ISSUE TITLE
Status.csv not updating

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#85]
Seems stuck on the UK

**Comment by joeHickson** [comment]
errors in the log, looking at it

**Comment by joeHickson** [comment]
pushed a hotfix, will await outcome.

**Comment by joeHickson** [comment]
It got pulled in for the cases run that's currently in progress. Will be a few hours for an outcome.

**Comment by seabbs** [comment]
Great stuff - looks sorted to me. Really great to have this info surfaced now. Will look at adding to the website. 

Looking at the results highlights an issue with regions being estimated once and then never updated (somewhere was last updated in August). Also, my immediate thought from here is that finding the one region that failed for cases and why is a bit tedious. I guess the best way of surfacing that info is via azure logging rather than anything else here?

**Comment by joeHickson** [comment]
If a dataset is showing a mixed result I would either go to runtimes.csv or server logs. I'm hoping we can get azure to filter to give us a report on failures but that's a little way down the road.
