### ISSUE TITLE
Truncation in UK test positive estimates.

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#88]
Looking at UK test positive estimates looks like delay to report has increased and our real time estimates are now biased downwards in some regions. @kathsherratt have you seen any data changes? May need to increase the time lag for this dataset only in order to avoid this for now. @joeHickson that should be possible now right?

**Comment by joeHickson** [comment]
Yes - add  `truncation = 123` to the dataset list.
Should we also expose the 12 week number in the same way for completeness? it seems odd to have param for one side of the window but not the other.

**Comment by seabbs** [comment]
Great - yes I think that is a good idea but as you say low priority.

**Comment by seabbs** [comment]
This is now critical. Looking at the UK page it appears that Rt is decreasing for test-positive cases. We need to know if this is due to truncation or is a real signal. @kathsherratt any progress on data changes? 

@joeHickson can you open a dummy PR indicating how to set truncation for just UK data sets (each one likely needs to be different). 

Unfortunately, I am on annual leave until Thursday so not available but happy to make these changes/do the exploration if no one else has any time.

**Comment by joeHickson** [comment]
raised the tangent as #102

**Comment by joeHickson** [comment]
@seabbs can I close this with the merge of #97?

**Comment by seabbs** [comment]
yes! thanks for work on this everyone.
