### ISSUE TITLE
Update/upgrade documentation

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#91]
Current documentation in the README is very targeted at those wishing to reproduce results. In reality, this will be a very small subset of the user base with most people interested in where to find the estimates, how to interact with them, the update schedule, and potentially links out to downstream uses of them.

Opened this issue to start a discussion on what an improved structure could be.

**Comment by joeHickson** [comment]
duplicate of #107 - I think the discussion is on there now
