### ISSUE TITLE
Remove old regions - UK cases

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-rt-estimates#93]
@joeHickson the regions that are no longer in the data should be the ones not updating here: https://github.com/epiforecasts/covid-rt-estimates/tree/master/subnational/united-kingdom/cases/national

Could you please remove from the production server asap. 

@kathsherratt could you review this to check these are the data sources that need to be removed.

**Comment by kathsherratt** [comment]
Yes, looks like the deprecated regions are no longer updating. 

But some estimates for these regions still appear in the "collated" csv output, for the cases and deaths sources. I think we just need to delete those files completely to stop the old estimates being collected up with the genuine "latest" files. 

I will put in a PR but don't want to cause any breaking changes in messing with the file system so this may need to be done by @joeHickson.

**Comment by seabbs** [comment]
Great stuff! Just merged so the csv will be fixed. Outstanding issue is that these estimates appear on the website sadly. @joeHickson fix for that is removing the old estimates from the production server. Kath's PR had a complete list.
